name: CI Workflow # 현재 워크플로우의 이름


on: # 워크플로우 실행 조건
  push:
    branches: [ "main" ]

jobs: # 실행할 작업 정의
  build:
    runs-on: ubuntu-latest # 실행 환경 설정

    steps: # job 안에서 실행될 단계
      - uses: actions/checkout@v3 # 현재 레포의 코드를 checkout(가져옴)

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # 제공자도 설정

      - name: 실행 권한 부여
        run: chmod +x gradlew

      - name: 빌드 및 테스트
        run: ./gradlew clean build

      # 깃헙에서 제공하는 환경변수를 활용해 해시값의 7자리만 가져옴
      - name: Docker Build 및 커밋 해시태그 설정
        run: |
          IMAGE_TAG=${GITHUB_SHA::7} 
          docker build -t myapp:$IMAGE_TAG .
